# Generated by Django 3.1.4 on 2021-01-07 16:05

from django.db import migrations, models
import django.db.models.deletion
import requests.request_actions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AddDoctor', requests.request_actions.AddDoctor), ('RemoveDoctor', requests.request_actions.RemoveDoctor)], max_length=30)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='account.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='account.profile')),
            ],
        ),
    ]
