# Generated by Django 3.1.4 on 2021-01-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[(1, 'ADD_DOCTOR'), (2, 'REMOVE_DOCTOR')], max_length=30),
        ),
    ]
