# Generated by Django 3.1.4 on 2021-01-11 22:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0002_auto_20210108_2212'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('sender', 'reciever', 'type')},
        ),
    ]
