# Generated by Django 3.1.4 on 2021-01-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20210107_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.IntegerField(choices=[(1, 'ADD_DOCTOR'), (2, 'REMOVE_DOCTOR')]),
        ),
    ]
