# Generated by Django 3.1.4 on 2021-02-20 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_used_for_predictions'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignment.specification'),
        ),
    ]
