# Generated by Django 3.1.3 on 2020-11-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201112_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='user_status',
            field=models.CharField(choices=[(1000, 'admin'), (1, 'patient'), (2, 'doctor')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user_status',
            field=models.CharField(choices=[(1000, 'admin'), (1, 'patient'), (2, 'doctor')], default=0, max_length=20),
        ),
    ]
