# Generated by Django 3.1.3 on 2020-11-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201112_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_status',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='user_status',
            field=models.CharField(choices=[(1000, 'admin'), (1, 'patient'), (2, 'doctor')], default=1, max_length=20),
        ),
    ]
