# Generated by Django 3.1.3 on 2020-11-12 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20201112_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='user_status',
        ),
    ]
