# Generated by Django 3.1.3 on 2020-11-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_baseuser_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('0', 'admin'), ('1', 'patient'), ('2', 'doctor')], default='1', max_length=1),
        ),
    ]
