# Generated by Django 3.1.4 on 2021-02-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_used_for_predictions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='used_for_predictions',
            new_name='used_for_prediction',
        ),
    ]
