# Generated by Django 3.1.3 on 2020-12-07 22:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20201207_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 7, 22, 47, 38, 740997, tzinfo=utc)),
        ),
    ]
