# Generated by Django 3.1.3 on 2020-12-07 22:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20201207_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 22, 54, 30, 756308, tzinfo=utc)),
        ),
    ]
