# Generated by Django 3.1.3 on 2020-12-08 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20201208_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 13, 47, 42, 844677, tzinfo=utc)),
        ),
    ]
