# Generated by Django 3.1.3 on 2020-12-08 15:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0008_auto_20201208_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user_id',
        ),
        migrations.AddField(
            model_name='assignment',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignments', to='assignment.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='account.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 15, 1, 20, 229678, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
