# Generated by Django 3.1.3 on 2020-12-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0014_auto_20201211_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='data',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.extradata'),
        ),
    ]
